batch_size: 256
exploration_steps: 128
evaluation_steps: 32
gradient_steps: 128
iterations: -1
max_buffer_size: 1000000
max_trajectory_length: 10
min_num_steps_before_training: 0
save_model: saved_models/debug/
environment:
  type: debug
  goal_position: 5.0
  goal_tolerance: 0.33
  min_start_position: 0.0
  max_start_position: 10.0
  pass_scale_interval_to_policy: false
  scale_action: true
model:
  discount_factor: 0.99
  exponential_weight: 0.005
  learning_rate_policy: 0.0003
  learning_rate_q: 0.0003
  network:
    hidden_size: 32
    number_of_hidden_layers: 2
  reward_scale: 3.0
  target_update_period: 1
  use_automatic_entropy_tuning: true
policy:
  type: tanh_gaussian
  network:
    hidden_size: 32
    number_of_hidden_layers: 2
