batch_size: 32
environment:
  type: debug
  goal_position: 5
  min_start_position: 0
  max_start_position: 10
environment_steps: 10
gradient_steps: 1
iterations: 1000
max_buffer_size: 100000
max_trajectory_length: 30
model:
  discount_factor: 0.99
  exponential_weight: 0.005
  learning_rate_policy: 0.001
  learning_rate_q: 0.001
  network:
    hidden_size: 16
    number_of_hidden_layers: 2
  reward_scale: 3.0
policy:
  type: gaussian
  network:
    hidden_size: 16
    number_of_hidden_layers: 2
save_model: null
