austenite_shear_modulus: 100000000000
austenitic_constant: 100000000
austenitic_finish_temperature: 71
austenitic_start_temperature: 59
critical_detwinning_finishing_stress: 1020000000.0
critical_detwinning_starting_stress: 500000000.0
delta_max: 1.0909090909090908
discount_factor: 0.99
environment_steps: 100
exponential_weight: 0.9
force_applied: 4
gradient_steps: 10
initial_deflection: 0
initial_force: 0
initial_martensitic_fraction_of_detwinned_martensite: 1
initial_position: 0.12
initial_temperature: 20
iterations: 100000
learning_rate_policy: 0.001
learning_rate_q: 0.001
learning_rate_value: 0.001
martensitic_constant: 40000000
martensitic_finish_temperature: 43
martensitic_start_temperature: 55
max_recoverable_deflection: 0.001
number_of_coils: 55
save_model: null
shear_stress: 1600000000.0
sigma_0: 1
spring_diameter: 0.0025
temperature: 0.1
twinned_martensite_shear_modulus: 50000000000
wire_diameter: 0.0005
