austenite_shear_modulus: 1
austenitic_constant: 1
austenitic_finish_temperature: 2
austenitic_start_temperature: 1
critical_detwinning_finishing_stress: 2
critical_detwinning_starting_stress: 1
discount_factor: 0.99
environment_steps: 100
exponential_weight: 0.9
final_pitch_angle: 0
final_spring_diameter: 0.2
gradient_steps: 10
initial_deflection_condition: 1
initial_force: 1
initial_martensitic_fraction_of_detwinned_martensite: 1
initial_martensitic_fraction_of_twinned_martensite: 1
initial_pitch_angle: 0
initial_spring_diameter: 0.1
initial_temperature: 293.15
intermediate_pitch_angle: 0
intermediate_spring_diameter: 0.15
iterations: 100000
learning_rate_policy: 0.001
learning_rate_q: 0.001
learning_rate_value: 0.001
martensitic_constant: 1
martensitic_finish_temperature: 2
martensitic_start_temperature: 1
max_recoverable_deflection: 1
number_of_coils: 10
save_model: null
shear_transformation_coefficient: 1
temperature: 0.1
twinned_martensite_shear_modulus: 1
wire_diameter: 0.005
